#!/usr/bin/env lua

-- Install font + icon_map.lua from the latest release
os.execute([[
  latest_tag=$(curl -fsSL https://api.github.com/repos/kvndrsslr/sketchybar-app-font/releases/latest \
    | jq -r .tag_name)

  if [ ! -f "$HOME/Library/Fonts/sketchybar-app-font.ttf" ]; then
    curl -fsSL -L \
      "https://github.com/kvndrsslr/sketchybar-app-font/releases/download/${latest_tag}/sketchybar-app-font.ttf" \
      -o "$HOME/Library/Fonts/sketchybar-app-font.ttf"
  fi

  if [ ! -f "$HOME/.config/sketchybar/helpers/app_icons.lua" ]; then
    output_path="$HOME/.config/sketchybar/helpers/app_icons.lua"
    mkdir -p "$(dirname "$output_path")"
    curl -fsSL \
      "https://github.com/kvndrsslr/sketchybar-app-font/releases/download/${latest_tag}/icon_map.lua" \
      -o "$output_path"
  fi
]])

-- Install SbarLua if missing
os.execute([[
  if [ ! -d "$HOME/.local/share/sketchybar_lua/" ]; then
    tmpdir=$(mktemp -d)
    git clone --depth=1 --quiet https://github.com/FelixKratz/SbarLua.git "$tmpdir"
    cd "$tmpdir" && make install
    rm -rf "$tmpdir"
  fi
]])

-- Load the sketchybar package and helpers
require("helpers")
require("init")
