alias tm="tmux new -A -s $(whoami)"
alias sp=". $HOME/dotfiles/set_proxy.sh \$1"
alias up="source $HOME/dotfiles/set_proxy.sh off"
alias ga="git add ."
alias gc="git commit -m ${1}"
alias gd="git diff"
alias gdt="git difftool"
alias gmt="git mergetool"
alias gp="git push ${1} ${2}"
alias gco="git checkout ${1} ${2}"
alias gpl="git pull ${1} ${2}"
alias grb="git rebase ${1} ${2}"
alias gs="git status"
alias la="ls -al"
alias lf="ls -al | grep ${1}"
alias ls="ls -Gl"
alias vv="$EDITOR ~/.vimrc"
alias zx="source ~/.zshrc"
alias zz="$EDITOR ~/.zshrc"
alias kr="defaults write -g ApplePressAndHoldEnabled -bool false"
alias knr="defaults write -g ApplePressAndHoldEnabled -bool true"
alias switch-keys="gpg-connect-agent \"scd serialno\" \"learn --force\" /bye"
alias flutter="fvm flutter"
alias pw="pass show -c"
alias pwo="pass otp show -c"

alias ibrew='arch -x86_64 /usr/local/bin/brew'

# nvim
alias nvim-lazy="NVIM_APPNAME=LazyVim nvim"
alias nvim-kick="NVIM_APPNAME=kickstart nvim"
alias nvim-chad="NVIM_APPNAME=NvChad nvim"
alias nvim-astro="NVIM_APPNAME=AstroNvim nvim"
